export default [
  {
    id: 1,
    name: "Tufted Chair",
    image_url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'chair',
    value: 305.88,
    assessments: 2.5,
    madeIn: 'Iceland',
    style: 'Gloves',
    color: 'azure',
    description: 'Natus deleniti nesciunt architecto quos optio commodi iste. Expedita et at perferendis odio est ut deleniti.'
  },
  {
    id: 2,
    name: "Wood Chair",
    image_url: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'chair',
    value: 27.32,
    assessments: 4.8,
    madeIn: 'Greenland',
    style: 'Ball',
    color: 'grey',
    description: 'Doloremque reiciendis nobis fugiat ut. Quo qui in alias in soluta non non cumque temporibus. Doloremque commodi sit rem molestiae quia quo minima nobis harum.'
  },
  {
    id: 3,
    name: "Simple Chair",
    image_url: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'chair',
    value: 816.87,
    assessments: 4.2,
    madeIn: 'Iran',
    style: 'Computer',
    color: 'lime',
    description: 'Voluptas vero et eius aliquam. Molestiae ut blanditiis iusto qui. Quisquam non voluptatum et eos voluptatum soluta maxime. Vero fugit maiores magni eos repellendus modi id exercitationem.'
  },
  {
    id: 4,
    name: "Wood Table",
    image_url: 'https://images.unsplash.com/photo-1581428982868-e410dd047a90?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&h=500',
    type: 'table',
    value: 294.71,
    assessments: 3.8,
    madeIn: 'Luxembourg',
    style: 'Pants',
    color: 'plum',
    description: 'Facere a delectus sunt quam facilis molestiae.'
  },
  {
    id: 5,
    name: "Garden Table",
    image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&h=500',
    type: 'table',
    value: 901.47,
    assessments: 4.6,
    madeIn: 'Congo',
    style: 'Gloves',
    color: 'lime',
    description: 'Autem excepturi iusto iure soluta. Qui modi cumque perspiciatis. Culpa eos ea dolorem eum et eos libero et sit. Animi fugiat sapiente nemo fugiat.'
  },
  {
    id: 6,
    name: "Beach Table",
    image_url: 'https://images.unsplash.com/photo-1537182534312-f945134cce34?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'table',
    value: 586.52,
    assessments: 2.2,
    madeIn: 'Libyan Arab Jamahiriya',
    style: 'Salad',
    color: 'azure',
    description: 'Accusantium iusto ducimus quia ratione aut saepe ea quam est. Ut ut sapiente cumque velit. Qui recusandae quis rem voluptatem. Aut minus illum consequatur facilis natus reprehenderit eos a cumque. Explicabo sit.'
  },
  {
    id: 7,
    name: "Bed Rustic",
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'bed',
    value: 108.14,
    assessments: 3.0,
    madeIn: 'Syrian Arab Republic',
    style: 'Sausages',
    color: 'turquoise',
    description: 'Voluptas ut eos magni dolorum. Quos quidem maiores consequatur vel eos officiis..'
  },
  {
    id: 8,
    name: "Prettier Bed",
    image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'bed',
    value: 848.52,
    assessments: 1.1,
    madeIn: 'Zimbabwe',
    style: 'Hat',
    color: 'white',
    description: 'Consectetur ad ad architecto odio quia optio. Et officiis impedit similique nihil officiis aut neque expedita quas. Est ducimus vero laboriosam quis earum.'
  },
  {
    id: 9,
    name: "Beautiful Bed",
    image_url: 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'bed',
    value: 44.64,
    assessments: 4.7,
    madeIn: 'Maldives',
    style: 'Shirt',
    color: 'teal',
    description: 'Cum vel repellat commodi numquam deserunt doloremque. Repellendus maiores rerum dicta expedita ut minima. Voluptatum a molestias sit. Vero delectus reiciendis..'
  },
  {
    id: 10,
    name: "Office Sofa",
    image_url: 'https://images.unsplash.com/photo-1545034210-264a82b4688b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'sofas',
    value: 414.27,
    assessments: 4.3,
    madeIn: 'Monaco',
    style: 'Chair',
    color: 'gold',
    description: 'Autem tempore fuga quia aut porro. Omnis iste reprehenderit qui. Sunt quaerat repudiandae quia harum. Architecto quidem neque quod voluptates nam.'
  },
  {
    id: 11,
    name: "Simple Sofa",
    image_url: 'https://images.unsplash.com/photo-1512212621149-107ffe572d2f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'sofas',
    value: 456.62,
    assessments: 3.4,
    madeIn: 'Morocco',
    style: 'Table',
    color: 'green',
    description: 'Id debitis facere. Consectetur eveniet voluptas repellendus.'
  },
  {
    id: 12,
    name: "Beko Sofa",
    image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&h=500',
    type: 'sofas',
    value: 666.93,
    assessments: 4.0,
    madeIn: 'Seychelles',
    style: 'Car',
    color: 'green',
    description: 'Et necessitatibus voluptatem iure id incidunt similique modi cum qui. Quia recusandae quos quod et.'
  },
  {
    id: 13,
    name: "Stool Woody",
    image_url: 'https://images.unsplash.com/photo-1557367184-663fba4b8b91?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'stools',
    value: 882.94,
    assessments: 3.6,
    madeIn: 'Virgin Islands, U.S.',
    style: 'Pants',
    color: 'sky blue',
    description: 'Id laborum accusamus et deleniti dolorem eveniet illo ut quia. Fuga consequatur qui vel aut in. Doloribus eos fugiat.'
  },
  {
    id: 14,
    name: "BPF Stool",
    image_url: 'https://images.unsplash.com/photo-1545805523-ccfc8657d739?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'stools',
    value: 998.41,
    assessments: 1.6,
    madeIn: 'Central African Republic',
    style: 'Shirt',
    color: 'magenta',
    description: 'Eum ratione nihil sequi dolorem ex dicta. Eum minus nam est ut.'
  },
  {
    id: 15,
    name: "Beko Stool",
    image_url: 'https://images.unsplash.com/photo-1590404805132-14deb6bc0b4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&h=500',
    type: 'stools',
    value: 567.51,
    assessments: 2.9,
    madeIn: 'Oman',
    style: 'Mouse',
    color: 'yellow',
    description: 'Eum et ut. Eos est possimus. Pariatur placeat necessitatibus porro rem necessitatibus. Aut nisi blanditiis dolor inventore.'
  }
];